### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by Suchty112** [LennardTFD/LeitstellenspielScripte#2]
> Alliance Building Hider
> Zählt die Anzahl an Fahrzeugen bei der Einsatzstelle

:D hötte ich dir vlt auch per pn schicken können. is nur ein kleiner Fehler :D 

Und noch ein gefunden:

> Needed Workers
> Berechnet mindest Personal um Fahrzeuge zu voll zu besetzen

**Comment by LennardTFD** [comment]
> 
> 
> > Alliance Building Hider
> > Zählt die Anzahl an Fahrzeugen bei der Einsatzstelle
> 
> :D hötte ich dir vlt auch per pn schicken können. is nur ein kleiner Fehler :D
> 
> Und noch ein gefunden:
> 
> > Needed Workers
> > Berechnet mindest Personal um Fahrzeuge zu voll zu besetzen

Wo ist der Fehler? 😄 finde ihn scheinbar nicht

**Comment by Suchty112** [comment]
beim Alliance Building Hider die Falsche Beschreibung :)

Und bei Needed Workers das doppelte zu.

**Comment by LennardTFD** [comment]
Scheint so als leben wir in unterschiedlichen Welten :D 
Das doppelte "zu" habe ich gefunden aber die Sache mit der falschen Beschreibung? 🤔 
Weder in der README.md noch in der Tampermonkey Datei kann ich das ganze nachvollziehen 😕

**Comment by Suchty112** [comment]
http://tinyurl.com/y5wgyh8q
Rote Pfeile könnten helfen :D

**Comment by LennardTFD** [comment]
AAHHHH!!! Danke fürs Bild :D Habe an der falschen Stelle gesucht.
