### ISSUE TITLE
Fehler beim Funktionsaufruf

### ISSUE THREAD

**Issue by lLittleBrother** [LennardTFD/LeitstellenspielScripte#6]
**Beschreibe den Fehler**
Die automatische Syntax-Prüfung hat einen Fehler gefunden in Zeile 47: "async function getTranslations()"

**Reproduktion**
Schritte um den Fehler nachzustellen:
1. Aktuellen Stand des Skripts in TamperMonkey aktivieren.
2. Bearbeiten Chatter to Speach öffnen
3. Im Menüband auf das Developer-Dropdown-Menu drücken und "Syntax-Überprüfung starten" auswählen.

**Was sollte eigentlich passieren**
Das Skript sollte verwendet werden können.

**Desktop (please complete the following information):**
 - Betriebssystem: Win10
 - Browser: Opera
 - Browser Version: 67.0.3575.97
 - Skript Version: 1.6
![Chatter2Speach](https://user-images.githubusercontent.com/63024617/78195901-21821d80-7481-11ea-8400-5d985f03299a.png)

**Comment by LennardTFD** [comment]
Könntest du den Fehler ein wenig weiter ausführen? Funktioniert das Script aufgrund dieses Fehlers nicht oder zeigt er nur einen Fehler in Tampermonkey an?
Sollte es nur dort angezeigt werden, sollte es eigentlich kein Problem in der Nutzung darstellen, da es bei Tampermonkey immer wieder zu Syntax Komplikationen kommt.
Konnte leider keine Fehler rekonstruieren. Weder in Form von Syntax makierungen noch in der Verwendung des Scripts.

LG Lennard
![noErrors](https://user-images.githubusercontent.com/38101963/79289629-163fe080-7eca-11ea-9f66-9628e664e800.PNG)

**Comment by lLittleBrother** [comment]
Hallo Lennard,

danke für deine Nachricht.
Ich habe zwischenzeitlich festgestellt, dass das Skript trotz des Syntax-Fehlers funktioniert.

Der Syntax-Fehler scheint nur angezeigt zu werden, wenn das Skript bearbeitet wurde.
Die Änderung kann aber trotzdem gespeichert werden und wird dann auch ausgeführt.

LG
LittleBrother 

Von meinem iPhone gesendet

**Comment by LennardTFD** [comment]
Dennoch danke fürs melden und sorry für die lange Wartezeit

LG Lennard
