### ISSUE TITLE
Poi Generator

### ISSUE THREAD

**Issue by Stiker839** [LennardTFD/LeitstellenspielScripte#7]
Der POI-Generator scheint nicht zu funktionieren, da es im Spiel keine Option gibt, ihn zu aktivieren.

**Comment by LennardTFD** [comment]
Script schon länger wegen hoher erwarteter Serverlast deaktiviert (Script würde für jeden zu generierenden POI eine Serveranfrage in kurzer Zeit stellen. Bei bspw. einem gewählten Radius von 2000m und dem POI Bushaltestelle biszu über Tausend)

Siehe eine der beiden Readme's
https://github.com/LennardTFD/LeitstellenspielScripte/blob/master/LSS_POIGenerator/README.md
https://github.com/LennardTFD/LeitstellenspielScripte/blob/master/README.md
