### ISSUE TITLE
Poi Generator

### ISSUE THREAD

**Issue by Stiker839** [LennardTFD/LeitstellenspielScripte#8]
Hey, mir ist klar, dass der Poi-Generator deaktiviert ist. Könnte ich eine Kopie für eine einzelne Person bekommen? Vielen Dank

**Comment by Stiker839** [comment]
Gibt es eine andere Plattform, auf der wir sprechen können?

**Comment by Stiker839** [comment]
Hallo, entschuldigen Sie die ständige Frage, ich habe es geschafft, eine frühere Version des Codes zum Laufen zu bringen. Ich könnte Ratschläge dazu geben, wie die API und das Poi funktionieren, da die API nicht von der Überführungsseite abgerufen wird. Wenn Sie helfen könnten, wäre das erstaunlich, es wäre nur für den persönlichen Gebrauch nichts anderes.

**Comment by LennardTFD** [comment]
Das Script ist aus gutem Grund deaktiviert. Es wird keine einzel Kopie geben. 
Ich übernehme keine Verantwortung für hohe Serverlasten die durch die Nutzung entstehen. Also nicht wundern sollte der Spielbetreiber auf entsprechende Nutzer zukommen.

Das Script sollte weiterhin funktionstüchtig sein aber bleibt für die allgemeinheit deaktiviert

Ps: Auch Spielbots sind ungern gesehen. Eine fork Version auf dem eigenen Github Account kommt sicherlich auch nicht gut.

**Comment by Stiker839** [comment]
Morgen kann ich den Großteil des Skripts zum Laufen bringen. Das einzige, was ich nicht hinter mich bringen kann, ist die tatsächliche Generation, da dies anscheinend nicht mehr funktioniert. Haben Sie das deaktiviert oder handelt es sich um ein Linkproblem?

**Comment by LennardTFD** [comment]
> Das Script ist aus gutem Grund deaktiviert. Es wird keine einzel Kopie geben. 
> Ich übernehme keine Verantwortung für hohe Serverlasten die durch die Nutzung entstehen. Also nicht wundern sollte der Spielbetreiber auf entsprechende Nutzer zukommen.
> 
> Das Script sollte weiterhin funktionstüchtig sein aber bleibt für die allgemeinheit deaktiviert
> 
> Ps: Auch Spielbots sind ungern gesehen. Eine fork Version auf dem eigenen Github Account kommt sicherlich auch nicht gut.

Ich Verweise auf meine letzte Mitteilung. Es ist nicht grundlos deaktiviert und der Nutzer ist für jeglichen Schaden durch Eigen- oder Fremdlasten selbst zu belangen
