### ISSUE TITLE
German to English Translation

### ISSUE THREAD

**Issue by jseeley2** [LennardTFD/LeitstellenspielScripte#9]
https://github.com/LennardTFD/LeitstellenspielScripte/blob/57b7393afe6623808efbc18828e097f3d5c5f247/LSS_MissionHeaderColorizer/missionHeaderColorizer.user.js#L1

Is there any way this Script can be made so it translates into english?

**Comment by LennardTFD** [comment]
Yeah. You can replace alle German occurences of text with english.
